CREATE OR ALTER PROCEDURE CREATE_CALL 
@VICTIMS_FULL_NAME varchar(240),
@CALL_TEXT varchar(4096),
@EMPLOYEE_ID int,
@LIST_BRIGADE_IDS VARCHAR(max),
@LIST_BUILDING_IDS VARCHAR(max)
AS
	DECLARE @CALL_ID as INT,@INDEX INT,@PREV INT,@WORD INT,@TEMP VARCHAR(120),
	@EMPLOYEE_SPECIALIZATION_NAME as VARCHAR(120);
	SET @INDEX = 1
	SET @PREV = 0

	SELECT TOP 1 @EMPLOYEE_SPECIALIZATION_NAME = spec.EMPLOYEE_SPECIALIZATION_NAME
	FROM (EMPLOYEES as emp
	LEFT JOIN EMPLOYEE_SPECIALIZATIONS as spec
	ON emp.EMPLOYEE_SPECIALIZATION_ID = spec.EMPLOYEE_SPECIALIZATION_ID)
	WHERE emp.EMPLOYEE_ID = @EMPLOYEE_ID;

	IF (@EMPLOYEE_SPECIALIZATION_NAME = 'Диспетчер')
		BEGIN
			INSERT INTO CALLS 
					(VICTIMS_FULL_NAME,CALL_TEXT,EMPLOYEE_ID) 
					VALUES 
					(@VICTIMS_FULL_NAME,@CALL_TEXT,@EMPLOYEE_ID);

			select @CALL_ID = scope_identity();

			WHILE @INDEX <= LEN(@LIST_BUILDING_IDS)
			BEGIN
				IF SUBSTRING(@LIST_BUILDING_IDS, @INDEX, 1) = ';'
					BEGIN
						SET @TEMP = SUBSTRING(@LIST_BUILDING_IDS, @PREV, @INDEX - @PREV)
						SET @PREV = @INDEX + 1

						INSERT INTO CALLS_BUILDINGS 
						(CALL_ID, BUILDING_ID) 
						VALUES 
						(@CALL_ID, cast(@TEMP as smallint));
					END	
					SET @INDEX = @INDEX + 1
			END

			SET @INDEX = 1
			SET @PREV = 0

			WHILE @INDEX <= LEN(@LIST_BRIGADE_IDS)
			BEGIN
				IF SUBSTRING(@LIST_BRIGADE_IDS, @INDEX, 1) = ';'
					BEGIN
						SET @TEMP = SUBSTRING(@LIST_BRIGADE_IDS, @PREV, @INDEX - @PREV)
						SET @PREV = @INDEX + 1

						INSERT INTO CALLS_BRIGADES
						(CALL_ID, BRIGADE_ID) 
						VALUES 
						(@CALL_ID, cast(@TEMP as smallint));
					END	
					SET @INDEX = @INDEX + 1
			END
		END
	ELSE
		BEGIN
			;THROW 51000, 'Звонок может принять только диспетчер', 1; 
		END
Go

EXEC CREATE_CALL 'egrergerfergerg', 'ergergefeg', 4, '1;3;' ,'1;'
