CREATE OR ALTER PROCEDURE UPDATE_CALL 
@CALL_ID as INT,
@VICTIMS_FULL_NAME varchar(240),
@CALL_TEXT varchar(4096),
@EMPLOYEE_ID int,
@LIST_BRIGADE_IDS VARCHAR(max),
@LIST_BUILDING_IDS VARCHAR(max),
@IS_PROCESSED bit,
@REPORT varchar(4096),
@BRIGADE_DISPATCH_TIME datetime,
@BRIGADE_ARRIVAL_TIME datetime,
@BRIGADE_RETURN_TIME datetime
AS
	DECLARE @INDEX INT,@PREV INT,@WORD INT,@TEMP VARCHAR(120),
	@EMPLOYEE_SPECIALIZATION_NAME as VARCHAR(120);
	SET @INDEX = 1
	SET @PREV = 0

	SELECT TOP 1 @EMPLOYEE_SPECIALIZATION_NAME = spec.EMPLOYEE_SPECIALIZATION_NAME
	FROM (EMPLOYEES as emp
	LEFT JOIN EMPLOYEE_SPECIALIZATIONS as spec
	ON emp.EMPLOYEE_SPECIALIZATION_ID = spec.EMPLOYEE_SPECIALIZATION_ID)
	WHERE emp.EMPLOYEE_ID = @EMPLOYEE_ID;

	IF (@EMPLOYEE_SPECIALIZATION_NAME = 'Диспетчер')
		BEGIN
			UPDATE CALLS 
			SET 
			VICTIMS_FULL_NAME = @VICTIMS_FULL_NAME,
			CALL_TEXT = @CALL_TEXT,
			EMPLOYEE_ID = @EMPLOYEE_ID,
			IS_PROCESSED = @IS_PROCESSED,
			REPORT = @REPORT,
			BRIGADE_DISPATCH_TIME = @BRIGADE_DISPATCH_TIME,
			BRIGADE_ARRIVAL_TIME = @BRIGADE_ARRIVAL_TIME,
			BRIGADE_RETURN_TIME = @BRIGADE_RETURN_TIME
			WHERE CALLS.CALL_ID = @CALL_ID;

			DELETE FROM CALLS_BUILDINGS
			WHERE CALL_ID = @CALL_ID

			DELETE FROM CALLS_BRIGADES
			WHERE CALL_ID = @CALL_ID

			WHILE @INDEX <= LEN(@LIST_BUILDING_IDS)
			BEGIN
				IF SUBSTRING(@LIST_BUILDING_IDS, @INDEX, 1) = ';'
					BEGIN
						SET @TEMP = SUBSTRING(@LIST_BUILDING_IDS, @PREV, @INDEX - @PREV)
						SET @PREV = @INDEX + 1

						INSERT INTO CALLS_BUILDINGS 
						(CALL_ID, BUILDING_ID) 
						VALUES 
						(@CALL_ID, cast(@TEMP as smallint));
					END	
					SET @INDEX = @INDEX + 1
			END

			SET @INDEX = 1
			SET @PREV = 0

			WHILE @INDEX <= LEN(@LIST_BRIGADE_IDS)
			BEGIN
				IF SUBSTRING(@LIST_BRIGADE_IDS, @INDEX, 1) = ';'
					BEGIN
						SET @TEMP = SUBSTRING(@LIST_BRIGADE_IDS, @PREV, @INDEX - @PREV)
						SET @PREV = @INDEX + 1

						INSERT INTO CALLS_BRIGADES
						(CALL_ID, BRIGADE_ID) 
						VALUES 
						(@CALL_ID, cast(@TEMP as smallint));
					END	
					SET @INDEX = @INDEX + 1
			END
		END
	ELSE
		BEGIN
			;THROW 51000, 'Звонок может принять только диспетчер', 1; 
		END
Go

EXEC UPDATE_CALL 1,'egrergerfergerg', 'ergergefeg', 1, '1;3;' ,'1;', 1, 'egregerg','2023-04-12','2023-05-12','2023-07-12'
