CREATE OR ALTER PROCEDURE GET_CALL_BUILDINGS @CALL_ID INT
AS
	SELECT BUILDINGS.BUILDING_ID, BUILDINGS.BUILDING_ID,
	BUILDINGS.BUILDING_ADDRESS, BUILDINGS.BUILDING_TYPE_ID,
	BUILDINGS.NUMBER_OF_FLOORS, BUILDING_TYPES.BUILDING_TYPE_NAME
	FROM CALLS_BUILDINGS
	LEFT JOIN BUILDINGS
	ON CALLS_BUILDINGS.BUILDING_ID = BUILDINGS.BUILDING_ID
	LEFT JOIN BUILDING_TYPES
	ON BUILDINGS.BUILDING_TYPE_ID = BUILDING_TYPES.BUILDING_TYPE_ID
	WHERE CALLS_BUILDINGS.CALL_ID = @CALL_ID
Go

EXEC GET_CALL_BUILDINGS 7
