CREATE OR ALTER PROCEDURE GET_CALL_BY_ID @CALL_ID INT 
AS
	SELECT CALLS.CALL_ID, CALLS.VICTIMS_FULL_NAME,CALLS.CALL_TIME,
	CALLS.CALL_TEXT,
	CALLS.REPORT,CALLS.BRIGADE_DISPATCH_TIME,
	CALLS.BRIGADE_ARRIVAL_TIME,CALLS.BRIGADE_RETURN_TIME,
	CALLS.EMPLOYEE_ID,
	EMPLOYEES.EMPLOYEE_NAME,EMPLOYEES.EMPLOYEE_SURNAME,
	EMPLOYEES.EMPLOYEE_FATHERS_NAME
	FROM CALLS
	LEFT JOIN EMPLOYEES
	ON CALLS.EMPLOYEE_ID = EMPLOYEES.EMPLOYEE_ID
	WHERE CALLS.CALL_ID = @CALL_ID
Go

EXEC GET_CALL_BY_ID 1
