CREATE OR ALTER PROCEDURE GET_CALL_BRIGADES @CALL_ID INT
AS
	SELECT BRIGADES.BRIGADE_ID, BRIGADES.BRIGADE_NAME
	FROM CALLS_BRIGADES
	LEFT JOIN BRIGADES
	ON CALLS_BRIGADES.BRIGADE_ID = BRIGADES.BRIGADE_ID
	WHERE CALLS_BRIGADES.CALL_ID = @CALL_ID
Go

EXEC GET_CALL_BRIGADES 7
