use fire_department;

--Таблицы типов
CREATE TABLE EMPLOYEE_SPECIALIZATIONS
(
EMPLOYEE_SPECIALIZATION_ID Smallint PRIMARY KEY identity,
EMPLOYEE_SPECIALIZATION_NAME varchar(120) NOT NULL UNIQUE,
);

CREATE TABLE EQUIPMENT_TYPES
(
EQUIPMENT_TYPE_ID Smallint PRIMARY KEY identity,
EQUIPMENT_TYPE_NAME varchar(120) NOT NULL UNIQUE,
);

CREATE TABLE BUILDING_TYPES
(
BUILDING_TYPE_ID Smallint PRIMARY KEY identity,
BUILDING_TYPE_NAME varchar(120) NOT NULL UNIQUE,
);

CREATE TABLE FIRE_SYSTEM_TYPES
(
FIRE_SYSTEM_TYPE_ID Smallint PRIMARY KEY identity,
FIRE_SYSTEM_TYPE_NAME varchar(120) NOT NULL UNIQUE,
);

--Основные таблицы

CREATE TABLE BRIGADES
(
BRIGADE_ID int PRIMARY KEY identity,
BRIGADE_NAME varchar(120) NOT NULL UNIQUE,
);

CREATE TABLE EMPLOYEES
(
EMPLOYEE_ID int PRIMARY KEY identity,
EMPLOYEE_NAME varchar(120) NOT NULL,
EMPLOYEE_SURNAME varchar(120) NOT NULL,
EMPLOYEE_FATHERS_NAME varchar(120) NOT NULL,
EMPLOYEE_PHONE_NUMBER varchar(120) NOT NULL UNIQUE,
EMPLOYEE_EMAIL varchar(120) NOT NULL UNIQUE,
EMPLOYEE_PASSWORD varchar(512) NOT NULL,
EMPLOYEE_SPECIALIZATION_ID Smallint NOT NULL FOREIGN KEY references EMPLOYEE_SPECIALIZATIONS(EMPLOYEE_SPECIALIZATION_ID),
BRIGADE_ID int FOREIGN KEY references BRIGADES(BRIGADE_ID) ON DELETE SET NULL,
);

CREATE TABLE EQUIPMENT
(
EQUIPMENT_ID int PRIMARY KEY identity,
INVENTORY_NUMBER varchar(120) NOT NULL UNIQUE,
EQUIPMENT_TYPE_ID Smallint NOT NULL FOREIGN KEY references EQUIPMENT_TYPES(EQUIPMENT_TYPE_ID),
);

CREATE TABLE BUILDINGS
(
BUILDING_ID int PRIMARY KEY identity,
BUILDING_ADDRESS varchar(240) NOT NULL UNIQUE,
NUMBER_OF_FLOORS smallint NOT NULL,
BUILDING_TYPE_ID Smallint NOT NULL FOREIGN KEY references BUILDING_TYPES(BUILDING_TYPE_ID),
);

CREATE TABLE CALLS
(
CALL_ID int PRIMARY KEY identity,
VICTIMS_FULL_NAME varchar(240) NOT NULL,
CALL_TIME datetime NOT NULL DEFAULT GETDATE(),
CALL_TEXT varchar(4096) NOT NULL,
REPORT varchar(4096),
BRIGADE_DISPATCH_TIME datetime,
BRIGADE_ARRIVAL_TIME datetime,
BRIGADE_RETURN_TIME datetime,
EMPLOYEE_ID int FOREIGN KEY references EMPLOYEES(EMPLOYEE_ID) ON DELETE SET NULL,
CONSTRAINT CK_BRIGADE_DISPATCH_TIME CHECK (BRIGADE_DISPATCH_TIME > CALL_TIME),
CONSTRAINT CK_BRIGADE_ARRIVAL_TIME CHECK (BRIGADE_ARRIVAL_TIME > BRIGADE_DISPATCH_TIME),
CONSTRAINT CK_BRIGADE_RETURN_TIME CHECK (BRIGADE_RETURN_TIME > BRIGADE_ARRIVAL_TIME),
);

CREATE TABLE SCHEDULE
(
SCHEDULE_ID int PRIMARY KEY identity,
START_DATE datetime NOT NULL,
END_DATE datetime NOT NULL,
BRIGADE_ID int FOREIGN KEY references BRIGADES(BRIGADE_ID) ON DELETE SET NULL,
EMPLOYEE_ID int FOREIGN KEY references EMPLOYEES(EMPLOYEE_ID) ON DELETE SET NULL,
CONSTRAINT CK_END_DATE CHECK (END_DATE > START_DATE),
CONSTRAINT CK_BRIGADE_EMPLOYEE_ID CHECK (BRIGADE_ID is not null OR EMPLOYEE_ID is not null),
);

-- Таблицы для связи многие-ко-многим

CREATE TABLE CALLS_BRIGADES
(
CALLS_BRIGADES_ID int PRIMARY KEY identity,
BRIGADE_ID int NOT NULL FOREIGN KEY references BRIGADES(BRIGADE_ID) ON DELETE CASCADE,
CALL_ID int NOT NULL FOREIGN KEY references CALLS(CALL_ID) ON DELETE CASCADE,
);

CREATE TABLE CALLS_BUILDINGS
(
CALLS_BUILDINGS_ID int PRIMARY KEY identity,
BUILDING_ID int NOT NULL FOREIGN KEY references BUILDINGS(BUILDING_ID) ON DELETE CASCADE,
CALL_ID int NOT NULL FOREIGN KEY references CALLS(CALL_ID) ON DELETE CASCADE
);

CREATE TABLE EQUIPMENT_BRIGADES
(
EQUIPMENT_BRIGADES_ID int PRIMARY KEY identity,
BRIGADE_ID int NOT NULL FOREIGN KEY references BRIGADES(BRIGADE_ID) ON DELETE CASCADE,
EQUIPMENT_ID int NOT NULL FOREIGN KEY references EQUIPMENT(EQUIPMENT_ID) ON DELETE CASCADE,
);

CREATE TABLE FIRE_SYSTEM_TYPES_BUILDINGS
(
FIRE_SYSTEM_TYPES_BUILDINGS_ID int PRIMARY KEY identity,
FIRE_SYSTEM_TYPE_ID smallint NOT NULL FOREIGN KEY references FIRE_SYSTEM_TYPES(FIRE_SYSTEM_TYPE_ID) ON DELETE CASCADE,
BUILDING_ID int NOT NULL FOREIGN KEY references BUILDINGS(BUILDING_ID) ON DELETE CASCADE,
);