CREATE OR ALTER PROCEDURE CountCallsByBuildingType @BuildingTypeName as varchar(120)
AS
BEGIN
    DECLARE @BUILDING_TYPE_ID as smallint;

	SELECT TOP 1 @BUILDING_TYPE_ID = BUILDING_TYPES.BUILDING_TYPE_ID 
	FROM BUILDING_TYPES
	WHERE BUILDING_TYPES.BUILDING_TYPE_NAME = @BuildingTypeName;

	SELECT COUNT(*) AS CallsCount
	FROM CALLS_BUILDINGS
	LEFT JOIN BUILDINGS
	ON CALLS_BUILDINGS.BUILDING_ID = BUILDINGS.BUILDING_ID
	WHERE BUILDINGS.BUILDING_TYPE_ID = @BUILDING_TYPE_ID
END
Go

EXEC CountCallsByBuildingType 'Административное'
