CREATE OR ALTER PROCEDURE GET_EQUIPMENT_BY_BRIGADE_IDS @BRIGADE_ID INT
AS
	SELECT EQUIPMENT.EQUIPMENT_ID, EQUIPMENT.INVENTORY_NUMBER,
	EQUIPMENT.EQUIPMENT_TYPE_ID, EQUIPMENT_TYPES.EQUIPMENT_TYPE_NAME
	FROM EQUIPMENT_BRIGADES
	LEFT JOIN EQUIPMENT
	ON EQUIPMENT_BRIGADES.EQUIPMENT_ID = EQUIPMENT.EQUIPMENT_ID
	LEFT JOIN EQUIPMENT_TYPES
	ON EQUIPMENT.EQUIPMENT_TYPE_ID = EQUIPMENT_TYPES.EQUIPMENT_TYPE_ID
	WHERE EQUIPMENT_BRIGADES.BRIGADE_ID = @BRIGADE_ID
Go

EXEC GET_EQUIPMENT_BY_BRIGADE_IDS 3
