CREATE OR ALTER PROCEDURE GET_EQUIPMENT
AS
	SELECT EQUIPMENT.EQUIPMENT_ID, EQUIPMENT.INVENTORY_NUMBER,EQUIPMENT.EQUIPMENT_TYPE_ID,
	EQUIPMENT_TYPES.EQUIPMENT_TYPE_NAME
	FROM EQUIPMENT
	LEFT JOIN EQUIPMENT_TYPES
	ON EQUIPMENT_TYPES.EQUIPMENT_TYPE_ID = EQUIPMENT.EQUIPMENT_TYPE_ID
	ORDER BY EQUIPMENT.EQUIPMENT_ID DESC
Go

EXEC GET_EQUIPMENT
