CREATE OR ALTER PROCEDURE GET_EQUIPMENT_BY_ID @EQUIPMENT_ID Int
AS
	SELECT EQUIPMENT.EQUIPMENT_ID, EQUIPMENT.INVENTORY_NUMBER,EQUIPMENT.EQUIPMENT_TYPE_ID,
	EQUIPMENT_TYPES.EQUIPMENT_TYPE_NAME
	FROM EQUIPMENT
	LEFT JOIN EQUIPMENT_TYPES
	ON EQUIPMENT_TYPES.EQUIPMENT_TYPE_ID = EQUIPMENT.EQUIPMENT_TYPE_ID
	WHERE EQUIPMENT.EQUIPMENT_ID = @EQUIPMENT_ID
Go

EXEC GET_EQUIPMENT_BY_ID 26
