CREATE OR ALTER PROCEDURE GET_SCHEDULE 
AS
	SELECT SCHEDULE.SCHEDULE_ID, SCHEDULE.START_DATE, SCHEDULE.END_DATE,
	SCHEDULE.BRIGADE_ID, SCHEDULE.EMPLOYEE_ID, BRIGADES.BRIGADE_NAME,
	EMPLOYEES.EMPLOYEE_NAME, EMPLOYEES.EMPLOYEE_SURNAME, EMPLOYEES.EMPLOYEE_FATHERS_NAME
	FROM SCHEDULE
	LEFT JOIN BRIGADES
	ON BRIGADES.BRIGADE_ID = SCHEDULE.BRIGADE_ID
	LEFT JOIN EMPLOYEES
	ON EMPLOYEES.EMPLOYEE_ID = SCHEDULE.EMPLOYEE_ID
	ORDER BY SCHEDULE.SCHEDULE_ID DESC
Go

EXEC GET_SCHEDULE
