CREATE OR ALTER PROCEDURE GET_EMPLOYEE_BY_EMAIL @EMPLOYEE_EMAIL as VARCHAR(120)
AS
	SELECT EMPLOYEE_ID, EMPLOYEE_NAME, EMPLOYEE_SURNAME,
	EMPLOYEE_FATHERS_NAME,EMPLOYEE_PHONE_NUMBER, EMPLOYEE_EMAIL, 
	EMPLOYEE_PASSWORD, emp.EMPLOYEE_SPECIALIZATION_ID,
	emp.BRIGADE_ID,EMPLOYEE_SPECIALIZATION_NAME, br.BRIGADE_NAME
	FROM EMPLOYEES emp
	LEFT JOIN
	EMPLOYEE_SPECIALIZATIONS spec
	ON emp.EMPLOYEE_SPECIALIZATION_ID = spec.EMPLOYEE_SPECIALIZATION_ID
	LEFT JOIN 
	BRIGADES br
	ON br.BRIGADE_ID = emp.BRIGADE_ID
	WHERE emp.EMPLOYEE_EMAIL = @EMPLOYEE_EMAIL
Go

EXEC GET_EMPLOYEE_BY_EMAIL '';
