CREATE OR ALTER PROCEDURE UPDATE_BUILDING @BUILDING_ID as INT, @BUILDING_ADDRESS VARCHAR(120),
@NUMBER_OF_FLOORS as smallint,@BUILDING_TYPE_ID as Smallint, @LIST_FIRE_SYSTEM_IDS VARCHAR(max)
AS
	DECLARE @INDEX INT,@PREV INT,@WORD INT,@TEMP VARCHAR(120);
	SET @INDEX = 1
	SET @PREV = 0

	UPDATE BUILDINGS 
	SET BUILDING_ADDRESS = @BUILDING_ADDRESS,
	NUMBER_OF_FLOORS = @NUMBER_OF_FLOORS,
	BUILDING_TYPE_ID = @BUILDING_TYPE_ID
	WHERE BUILDINGS.BUILDING_ID = @BUILDING_ID

	DELETE FROM FIRE_SYSTEM_TYPES_BUILDINGS
	WHERE BUILDING_ID = @BUILDING_ID

	WHILE @INDEX <= LEN(@LIST_FIRE_SYSTEM_IDS)
	BEGIN
		IF SUBSTRING(@LIST_FIRE_SYSTEM_IDS, @INDEX, 1) = ';'
			BEGIN
				SET @TEMP = SUBSTRING(@LIST_FIRE_SYSTEM_IDS, @PREV, @INDEX - @PREV)
				SET @PREV = @INDEX + 1

				INSERT INTO FIRE_SYSTEM_TYPES_BUILDINGS 
				(FIRE_SYSTEM_TYPE_ID,BUILDING_ID) 
				VALUES 
				(cast(@TEMP as smallint),@BUILDING_ID);
			END	
			SET @INDEX = @INDEX + 1
	END
Go

EXEC UPDATE_BUILDING 26,'egr3ergergerg', 2, 1, '1;2;3;4;'
