CREATE OR ALTER PROCEDURE GET_BUILDING_BY_ID @BUILDING_ID Int
AS
	SELECT BUILDINGS.BUILDING_ID, BUILDINGS.BUILDING_ADDRESS, BUILDINGS.NUMBER_OF_FLOORS,
	BUILDINGS.BUILDING_TYPE_ID, BUILDING_TYPES.BUILDING_TYPE_NAME
	FROM BUILDINGS
	LEFT JOIN BUILDING_TYPES
	ON BUILDINGS.BUILDING_TYPE_ID = BUILDING_TYPES.BUILDING_TYPE_ID
	WHERE BUILDINGS.BUILDING_ID = @BUILDING_ID
Go

EXEC GET_BUILDING_BY_ID 26
