CREATE OR ALTER PROCEDURE GET_BUILDINGS 
AS
	SELECT BUILDINGS.BUILDING_ID, BUILDINGS.BUILDING_ADDRESS, BUILDINGS.NUMBER_OF_FLOORS,
	BUILDINGS.BUILDING_TYPE_ID, BUILDING_TYPES.BUILDING_TYPE_NAME
	FROM BUILDINGS
	LEFT JOIN BUILDING_TYPES
	ON BUILDINGS.BUILDING_TYPE_ID = BUILDING_TYPES.BUILDING_TYPE_ID
	ORDER BY BUILDINGS.BUILDING_ID DESC
Go

EXEC GET_BUILDINGS
