CREATE OR ALTER PROCEDURE CREATE_BUILDING @BUILDING_ADDRESS VARCHAR(120),
@NUMBER_OF_FLOORS as smallint,@BUILDING_TYPE_ID as Smallint, @LIST_FIRE_SYSTEM_IDS VARCHAR(max)
AS
	DECLARE @BUILDING_ID as INT,@INDEX INT,@PREV INT,@WORD INT,@TEMP VARCHAR(120);
	SET @INDEX = 1
	SET @PREV = 0

	INSERT INTO BUILDINGS 
			(BUILDING_ADDRESS,NUMBER_OF_FLOORS,BUILDING_TYPE_ID) 
			VALUES 
			(@BUILDING_ADDRESS,@NUMBER_OF_FLOORS,@BUILDING_TYPE_ID);

	select @BUILDING_ID = scope_identity();

	WHILE @INDEX <= LEN(@LIST_FIRE_SYSTEM_IDS)
	BEGIN
		IF SUBSTRING(@LIST_FIRE_SYSTEM_IDS, @INDEX, 1) = ';'
			BEGIN
				SET @TEMP = SUBSTRING(@LIST_FIRE_SYSTEM_IDS, @PREV, @INDEX - @PREV)
				SET @PREV = @INDEX + 1

				INSERT INTO FIRE_SYSTEM_TYPES_BUILDINGS 
				(FIRE_SYSTEM_TYPE_ID,BUILDING_ID) 
				VALUES 
				(cast(@TEMP as smallint),@BUILDING_ID);
			END	
			SET @INDEX = @INDEX + 1
	END
Go

EXEC CREATE_BUILDING 'egrergergerg', 2, 1, '1;2;3;4;'
