CREATE OR ALTER PROCEDURE UPDATE_BRIGADE @BRIGADE_ID int, @BRIGADE_NAME VARCHAR(120),
@LIST_EQUIPMENT_IDS VARCHAR(max)
AS
	DECLARE @INDEX INT,@PREV INT,@WORD INT,@TEMP VARCHAR(120);
	SET @INDEX = 1
	SET @PREV = 0

	UPDATE BRIGADES 
	SET BRIGADE_NAME = @BRIGADE_NAME
	WHERE BRIGADES.BRIGADE_ID = @BRIGADE_ID;

	DELETE EQUIPMENT_BRIGADES
	WHERE EQUIPMENT_BRIGADES.BRIGADE_ID = @BRIGADE_ID;

	WHILE @INDEX <= LEN(@LIST_EQUIPMENT_IDS)
	BEGIN
		IF SUBSTRING(@LIST_EQUIPMENT_IDS, @INDEX, 1) = ';'
			BEGIN
				SET @TEMP = SUBSTRING(@LIST_EQUIPMENT_IDS, @PREV, @INDEX - @PREV)
				SET @PREV = @INDEX + 1

				INSERT INTO EQUIPMENT_BRIGADES
				(EQUIPMENT_ID,BRIGADE_ID) 
				VALUES 
				(cast(@TEMP as int),@BRIGADE_ID);
			END	
			SET @INDEX = @INDEX + 1
	END
Go

EXEC UPDATE_BRIGADE 15,'egrerfge4d3f1rgerg1','1;2;'
