CREATE OR ALTER PROCEDURE CREATE_BRIGADE @BRIGADE_NAME VARCHAR(120),
@LIST_EQUIPMENT_IDS VARCHAR(max)
AS
	DECLARE @BRIGADE_ID as INT,@INDEX INT,@PREV INT,@WORD INT,@TEMP VARCHAR(120);
	SET @INDEX = 1
	SET @PREV = 0

	INSERT INTO BRIGADES 
			(BRIGADE_NAME) 
			VALUES 
			(@BRIGADE_NAME);

	select @BRIGADE_ID = scope_identity();

	WHILE @INDEX <= LEN(@LIST_EQUIPMENT_IDS)
	BEGIN
		IF SUBSTRING(@LIST_EQUIPMENT_IDS, @INDEX, 1) = ';'
			BEGIN
				SET @TEMP = SUBSTRING(@LIST_EQUIPMENT_IDS, @PREV, @INDEX - @PREV)
				SET @PREV = @INDEX + 1

				INSERT INTO EQUIPMENT_BRIGADES
				(EQUIPMENT_ID,BRIGADE_ID) 
				VALUES 
				(cast(@TEMP as int),@BRIGADE_ID);
			END	
			SET @INDEX = @INDEX + 1
	END
Go

EXEC CREATE_BRIGADE 'egrerfge4d3f1rgerg1','1;2;'
